[package]
name = "garlickboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# miniquad="0.3.15"
# pixel-canvas = "0.2.3"